name: Deploy Go via CDK

env:
  AWSCERT: arn:aws:acm:ap-southeast-1:407461997746:certificate/87b0fd84-fb44-4782-b7eb-d9c7f8714908

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  staging:
    runs-on: ubuntu-latest
    name: Deploy to staging
    environment:
      name: staging
      url: https://stghello.dabase.com
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: ap-southeast-1
      - uses: actions/setup-node@v4
      - name: Run CDK deploy
        run: |
          npx aws-cdk@2.x deploy --require-approval never
        env:
          DOMAIN: stghello.dabase.com
          VERSION: ${{ github.sha }}

  production:
    runs-on: ubuntu-latest
    name: Deploy to production
    environment:
      name: production
      url: https://hello.dabase.com
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: ap-southeast-1
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Run CDK deploy
        run: |
          npx aws-cdk@2.x deploy --require-approval never
        env:
          DOMAIN: hello.dabase.com
          VERSION: ${{ github.sha }}
