name: Deploy Go via CDK

env:
  AWSCERT: arn:aws:acm:eu-west-2:407461997746:certificate/9083a66b-72b6-448d-9bce-6ee2e2e52e36

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  staging:
    runs-on: ubuntu-latest
    name: Deploy to staging
    environment:
      name: staging
      url: https://stghello.dabase.com
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: eu-west-2
      - uses: actions/setup-node@v4
      - name: Run CDK deploy
        run: |
          make -C src/
          npx aws-cdk@2.x deploy --require-approval never
        env:
          DOMAIN: stghello.dabase.com
          VERSION: ${{ github.sha }}


  production:
    runs-on: ubuntu-latest
    needs: staging
    name: Deploy to production
    environment:
      name: production
      url: https://hello.dabase.com
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: |
          make -C src/ build
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: eu-west-2
      - uses: actions/setup-node@v4
      - name: Run CDK deploy
        run: |
          make -C src/
          npx aws-cdk@2.x deploy --require-approval never
        env:
          DOMAIN: hello.dabase.com
          VERSION: ${{ github.sha }}
