name: Deploy Go via CDK

env:
  AWSCERT: arn:aws:acm:eu-west-2:407461997746:certificate/9083a66b-72b6-448d-9bce-6ee2e2e52e36
  CLOUDFLARE_ACCOUNT_ID: "212aab16e8e2f88974a456b8097b2726"
  CLOUDFLARE_ZONE_ID: "dabase.com"

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  staging:
    runs-on: ubuntu-latest
    name: Deploy to staging
    environment:
      name: staging
      url: https://stghello.dabase.com
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: golang/govulncheck-action@v1
      - uses: golangci/golangci-lint-action@v6
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: eu-west-2
      - uses: actions/setup-node@v4
      - name: Run CDK deploy
        run: |
          make -C src/
          npx aws-cdk@2.x deploy --require-approval never --outputs-file outputs.json
        env:
          DOMAIN: stghello.dabase.com
      - name: Read CDK outputs
        id: cdk-outputs
        run: echo "api_domain=$(jq -r '."stghello-dabase-com".APIGatewayDomain' outputs.json)" >> $GITHUB_OUTPUT
      - name: Update Cloudflare DNS
        uses: everpcpc/cloudflare-dns-action@v1
        with:
          type: "CNAME"
          name: "stghello.dabase.com"
          content: ${{ steps.cdk-outputs.outputs.api_domain }}
          ttl: 1
          proxied: false
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE }}
      - name: Verify DNS
        run: |
          EXPECTED=$(jq -r '."stghello-dabase-com".APIGatewayDomain' outputs.json)
          ACTUAL=$(dig +short CNAME stghello.dabase.com | tr -d .)
          echo "Expected API Gateway Domain: $EXPECTED"
          echo "Actual CNAME record: $ACTUAL"
          [ "$EXPECTED" = "$ACTUAL" ] && echo "✅ DNS is correctly configured" || { echo "❌ DNS configuration mismatch" ; exit 1; }
      - run: curl https://stghello.dabase.com

  production:
    runs-on: ubuntu-latest
    needs: staging
    name: Deploy to production
    environment:
      name: production
      url: https://hello.dabase.com
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: |
          make -C src/ build
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: eu-west-2
      - uses: actions/setup-node@v4
      - name: Run CDK deploy
        run: |
          make -C src/
          npx aws-cdk@2.x deploy --require-approval never --outputs-file outputs.json
        env:
          DOMAIN: hello.dabase.com
      - name: Read CDK outputs
        id: cdk-outputs-prod
        run: echo "api_domain=$(jq -r '."hello-dabase-com".APIGatewayDomain' outputs.json)" >> $GITHUB_OUTPUT
      - name: Update Cloudflare DNS
        uses: everpcpc/cloudflare-dns-action@v1
        with:
          type: "CNAME"
          name: "hello.dabase.com"
          content: ${{ steps.cdk-outputs-prod.outputs.api_domain }}
          ttl: 1
          proxied: false
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE }}
      - name: Verify DNS
        run: |
          EXPECTED=$(jq -r '."hello-dabase-com".APIGatewayDomain' outputs.json)
          ACTUAL=$(dig +short CNAME hello.dabase.com | tr -d .)
          echo "Expected API Gateway Domain: $EXPECTED"
          echo "Actual CNAME record: $ACTUAL"
          [ "$EXPECTED" = "$ACTUAL" ] && echo "✅ DNS is correctly configured" || { echo "❌ DNS configuration mismatch" ; exit 1; }
      - run: curl https://hello.dabase.com
