name: Deploy Go via CDK

env:
  AWSCERT: arn:aws:acm:eu-west-2:407461997746:certificate/9083a66b-72b6-448d-9bce-6ee2e2e52e36
  CLOUDFLARE_ACCOUNT_ID: "212aab16e8e2f88974a456b8097b2726"
  CLOUDFLARE_ZONE_ID: "dabase.com"

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  staging:
    runs-on: ubuntu-latest
    name: Deploy to staging
    environment:
      name: staging
      url: https://stghello.dabase.com
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: golang/govulncheck-action@v1
      - uses: golangci/golangci-lint-action@v6
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: eu-west-2
      - uses: actions/setup-node@v4
      - name: Run CDK deploy
        run: |
          make -C src/
          npx aws-cdk@2.x deploy --require-approval never --outputs-file outputs.json
        env:
          DOMAIN: stghello.dabase.com
      - name: Update Cloudflare DNS
        run: |
          APIGATEWAY_DOMAIN=$(jq -r '."stghello-dabase-com".APIGatewayDomain' outputs.json)
          # Get the DNS record ID first
          RECORD_ID=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records?type=CNAME&name=stghello.dabase.com" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" | jq -r '.result[0].id')
          
          # Update the CNAME record
          curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records/$RECORD_ID" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data "{\"type\":\"CNAME\",\"name\":\"stghello\",\"content\":\"$APIGATEWAY_DOMAIN\",\"ttl\":1,\"proxied\":false}"
      - name: Verify DNS
        run: |
          EXPECTED=$(jq -r '."stghello-dabase-com".APIGatewayDomain' outputs.json)
          ACTUAL=$(dig +short CNAME stghello.dabase.com | tr -d .)
          echo "Expected API Gateway Domain: $EXPECTED"
          echo "Actual CNAME record: $ACTUAL"
          [ "$EXPECTED" = "$ACTUAL" ] && echo "✅ DNS is correctly configured" || { echo "❌ DNS configuration mismatch" ; exit 1; }
      - run: curl https://stghello.dabase.com

  production:
    runs-on: ubuntu-latest
    needs: staging
    name: Deploy to production
    environment:
      name: production
      url: https://hello.dabase.com
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: |
          make -C src/ build
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: eu-west-2
      - uses: actions/setup-node@v4
      - name: Run CDK deploy
        run: |
          make -C src/
          npx aws-cdk@2.x deploy --require-approval never --outputs-file outputs.json
        env:
          DOMAIN: hello.dabase.com
      - name: Update Cloudflare DNS
        run: |
          APIGATEWAY_DOMAIN=$(jq -r '."hello-dabase-com".APIGatewayDomain' outputs.json)
          # Get the DNS record ID first
          RECORD_ID=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records?type=CNAME&name=hello.dabase.com" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" | jq -r '.result[0].id')
          
          # Update the CNAME record
          curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records/$RECORD_ID" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data "{\"type\":\"CNAME\",\"name\":\"hello\",\"content\":\"$APIGATEWAY_DOMAIN\",\"ttl\":1,\"proxied\":false}"
      - name: Verify DNS
        run: |
          EXPECTED=$(jq -r '."hello-dabase-com".APIGatewayDomain' outputs.json)
          ACTUAL=$(dig +short CNAME hello.dabase.com | tr -d .)
          echo "Expected API Gateway Domain: $EXPECTED"
          echo "Actual CNAME record: $ACTUAL"
          [ "$EXPECTED" = "$ACTUAL" ] && echo "✅ DNS is correctly configured" || { echo "❌ DNS configuration mismatch" ; exit 1; }
      - run: curl https://hello.dabase.com
